### ISSUE TITLE
Support for new chrome webstore

### ISSUE THREAD

**Issue by vpn** [Rob--W/crxviewer#134]
Request to add support for new chrome webstore
Uses a new URL format:
https://chromewebstore.google.com/detail/chrome-extension-source-v/jifpbeccnghkjeaalbbjmodiffmgedin

**Comment by xnumad** [comment]
Obvious workaround for now: rewrite new URL to old URL, enter old URL

**Comment by Rob--W** [comment]
Re-opening until I have published the update, to avoid more duplicate bug reports.

**Comment by Rob--W** [comment]
I have published the update as version 1.7.0:

- Already approved in Firefox, at https://addons.mozilla.org/firefox/addon/crxviewer/
- Pending review in the Chrome Web Store, at https://chrome.google.com/webstore/detail/chrome-extension-source-v/jifpbeccnghkjeaalbbjmodiffmgedin
- Online demo published on my website at https://robwu.nl/crxviewer/

I have not been able to update the Opera version, because the developer dashboard is currently broken.
