### ISSUE TITLE
Feature request: Add hash file function

### ISSUE THREAD

**Issue by ngyikp** [Rob--W/crxviewer#35]
It would be great to have a way to hash files by MD5/SHA1 to detect legit minified JavaScript libraries and fake ones with extra injected code.

**Comment by Rob--W** [comment]
Sounds good. Maybe even with a list of known libraries *, or inputting an external URL to verify that the two files match.

\* e.g. from https://github.com/mozilla/amo-validator/blob/master/validator/testcases/hashes-allowed.txt

Another thing to consider is trailing whitespace. I have seen too often that a hash does not match because of a difference in whitespace.

**Comment by Rob--W** [comment]
I published version 1.5, which adds a "Show analysis" button to the toolbar of a file. Upon click it shows the hashes of the file.
