### ISSUE TITLE
Addon seems to be causing sync issues on Firefox

### ISSUE THREAD

**Issue by aroskuski** [Rob--W/crxviewer#38]
I've been noticing a bunch of sync errors showing up in my Firefox sync logs recently which seem to be caused by this extension. The error message looks like this:
```
1496285752154	Sync.Engine.Extension-Storage	ERROR	Syncing crxviewer-firefox@robwu.nl: request failed: Error: HTTP 507 Insufficient Storage: Resource access is forbidden for this user (Collection maximum size exceeded (102426 > 102400 Bytes).) (resource://gre/modules/services-common/kinto-http-client.js:1924:25) JS Stack trace: [10]</request/</<@kinto-http-client.js:1924:25 < waitForSyncCallback@async.js:98:7 < makeSpinningCallback/callback.wait@async.js:168:27 < promiseSpinningly@async.js:234:12 < _sync@extension-storage.js:47:12 < WrappedNotify@util.js:164:21 < sync@engines.js:696:5 < _syncEngine@enginesync.js:320:7 < sync@enginesync.js:167:15 < onNotify@service.js:1310:7 < WrappedNotify@util.js:164:21 < WrappedLock@util.js:120:16 < _lockedSync@service.js:1300:12 < sync/<@service.js:1292:14 < WrappedCatch@util.js:95:16 < sync@service.js:1281:5 < waitForSyncCallback@async.js:98:7 < makeSpinningCallback/callback.wait@async.js:168:27 < _handlerListener@addonsreconciler.js:633:9 < onEnabled@addonsreconciler.js:645:5 < callAddonListeners@AddonManager.jsm:1739:11 < callAddonListeners@AddonManager.jsm:3190:5 < updateAddonDisabledState@XPIProvider.jsm:5035:11 < set userDisabled@XPIProvider.jsm:7486:9 < doCommand@extensions.js:1231:9 < doCommand@extensions.js:1524:5 < initialize/<@extensions.js:196:5
```
The problem seems to go away when the extension is disabled.

This is using Firefox 53.0.3 on Ubuntu 17.04.

**Comment by Rob--W** [comment]
The message suggests that too much data is saved (over 100kb). My add-on however only saves a few boolean values, so I don't believe that my add-on logic is the root cause of the sync error.
Have you installed any other WebExtensions add-ons that use the `storage.sync` API? If you aren't sure, send me the list of add-ons that you've installed and I can take a look.

In the stack trace that you shared, I looked at extension-storage.js (`resource://gre/modules/services-sync/engines/extension-storage.js` in Firefox 53) and found that `_sync` [is](http://searchfox.org/mozilla-central/rev/3efd1caff252061946f0773df68bdd50de5eb756/services/sync/modules/engines/extension-storage.js#40-42):

```js
  _sync() {
    return Async.promiseSpinningly(ExtensionStorageSync.syncAll());
  },
```

The referenced `syncAll` method is implemented in http://searchfox.org/mozilla-central/rev/972b7a5149bbb2eaab48aafa87678c33d5f2f045/toolkit/components/extensions/ExtensionStorageSync.jsm#732-777.
... which seems to iterate over all extensions, generate the new value and save the result. To debug, I would do the following:

1. Visit about:debugging and enable "Enable add-on debugging".
2. Open the browser toolbox (Ctrl-Alt-Shift-I)
3. Click on the "Debugger" tab
4. Search for "ExtensionStorageSync.js" in the searchbox to navigate to the given file.
5. Put breakpoints at interesting places in the code.
6. Do your thing to trigger the error (according to the report: enable the add-on).
7. When the breakpoint is triggered, step through and check whether the values make sense. In particular, try to see where the value that exceeds 100kb is coming from. 

@aroskuski Could you follow the above steps and see if you find anything relevant?
(When I run step 4 locally (in a new profile) I don't see any matching file, possibly because I don't use Firefox Sync.)

This is the stack trace from the initial report, with line breaks added for readability:
```
1496285752154	Sync.Engine.Extension-Storage	ERROR
Syncing crxviewer-firefox@robwu.nl: request failed:
Error: HTTP 507 Insufficient Storage: Resource access is forbidden for this user (Collection maximum size exceeded (102426 > 102400 Bytes).)
(resource://gre/modules/services-common/kinto-http-client.js:1924:25)
JS Stack trace: [10]
</request/</<@kinto-http-client.js:1924:25
< waitForSyncCallback@async.js:98:7
< makeSpinningCallback/callback.wait@async.js:168:27
< promiseSpinningly@async.js:234:12
< _sync@extension-storage.js:47:12
< WrappedNotify@util.js:164:21
< sync@engines.js:696:5
< _syncEngine@enginesync.js:320:7
< sync@enginesync.js:167:15
< onNotify@service.js:1310:7
< WrappedNotify@util.js:164:21
< WrappedLock@util.js:120:16
< _lockedSync@service.js:1300:12
< sync/<@service.js:1292:14
< WrappedCatch@util.js:95:16
< sync@service.js:1281:5
< waitForSyncCallback@async.js:98:7
< makeSpinningCallback/callback.wait@async.js:168:27
< _handlerListener@addonsreconciler.js:633:9
< onEnabled@addonsreconciler.js:645:5
< callAddonListeners@AddonManager.jsm:1739:11
< callAddonListeners@AddonManager.jsm:3190:5
< updateAddonDisabledState@XPIProvider.jsm:5035:11
< set userDisabled@XPIProvider.jsm:7486:9
< doCommand@extensions.js:1231:9
< doCommand@extensions.js:1524:5
< initialize/<@extensions.js:196:5
```

**Comment by aroskuski** [comment]
Sorry it took so long for me to get back to you on this, I completely forgot about this issue.

Regardless, the problem seems to have gone away by itself, so I'll close this for now.
