### ISSUE TITLE
support versions of extensions

### ISSUE THREAD

**Issue by grahamperrin** [Rob--W/crxviewer#39]
https://addons.mozilla.org/en-GB/firefox/addon/diigo-web-collector/versions/?page=1#version-5.1.0.38.1-signed.1-signed for example, I might be more interested in Diigo Toolbar 5.x than in more recent Diigo Web Collector 3.x

Another example: https://addons.mozilla.org/firefox/addon/vertical-tabs-reloaded/versions/beta there's 0.8.4-alpha but Extension source viewer appears to show code for an earlier version.

**Comment by Rob--W** [comment]
Right-click on the "Add to Firefox" button (the link to the xpi file) and choose the "View linked extension source" option if you want to see a specific version.

This context menu option is currently based on the link target; in order to show a specific version, the URL should contain all necessary information to build the XPI URL. The /versions/ URL does not contain the numeric ID of the XPI file, so it is not easy to determine the correct URL. It could be done by fetching the linked add-on page and trying to find the xpi URL from it, but since AMO's front-end is going to change significantly, I'm not keen on doing that. An alternative is to find enough parameters in the URL and use AMO's API (e.g. see #34) to find the XPI URL, but that is complicated too.

**Comment by Rob--W** [comment]
Version 1.6.6 includes the ability to select a different version in the viewer itself. Click on the "Open" link to see the "Find XPI files of Firefox add-ons at AMO" form.

**Comment by grahamperrin** [comment]
Confirmed. Thanks! 

moz-extension://5b0f4f55-fc02-49f4-9d6f-03183fcfa2dc/crxviewer.html?noview=on&crx=https%3A//addons.mozilla.org/firefox/downloads/latest/diigo-web-collector/platform%3A2/diigo-web-collector.xpi
▶ Search on AMO 

- finds twenty-one recent results.

**Comment by Rob--W** [comment]
`moz-extension` links don't work on Github, here is one via the online demo:
https://robwu.nl/crxviewer/?noview=on&crx=https%3A//addons.mozilla.org/firefox/downloads/latest/diigo-web-collector/platform%3A2/diigo-web-collector.xpi

Note that I only display the 25 most recent versions (and potentially multiple platforms per version). That ought be sufficient, but if not, I am willing to add a pager.
