### ISSUE TITLE
Download button ignores preference setting

### ISSUE THREAD

**Issue by restcure** [Rob--W/crxviewer#54]
No matter whether or not set to ask for download folder, download goes to whatever default folder is is indicated.  in Firefox (57, at least) no save folder selection dialog comes up - just saves to whatever default folder.  It's not that much of a problem with Chrome, since the desired download folder can be selected when the confirmation opens (set to the default folder, ignoring the folder previously selected) but still ...

**Comment by Rob--W** [comment]
My extension [uses the `downloads.download` function](https://github.com/Rob--W/crxviewer/blob/53b6abbb78549e9dad076288c35f4271bf28ad53/src/background.js#L267-L275)) to provide downloads, and the preferences should be respected, [according to the documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/download):

>  the browser will show the file chooser or not based on the general user preference for this behavior (in Firefox this preference is labeled "Always ask you where to save files" in about:preferences, or browser.download.useDownloadDir in about:config).

This does not seem to happen in Firefox 57, but that looks like a bug which is fixed in Firefox 58 (https://bugzilla.mozilla.org/show_bug.cgi?id=1394851). Can you wait for Firefox 58, or would you like to have a work-around?

**Comment by restcure** [comment]
It seems that I've inadvertently waited.  Does work with 58, aaaaand ... there we go.
