### ISSUE TITLE
Add addons-dev.allizom.org and addons.allizom.org

### ISSUE THREAD

**Issue by nt1m** [Rob--W/crxviewer#72]

**Comment by Rob--W** [comment]
Hi Tim, good to see you here :)

This is a reasonable feature request. Where did you encounter the need for this?

There are two places in the codebase where the AMO domain is hardcoded:

- https://github.com/Rob--W/crxviewer/blob/96b9e8e08381842c10ba82e5c79a77f8abe6671a/src/cws_pattern.js
- [https://github.com/Rob--W/crxviewer/blob/96b9e8e08381842c10ba82e5c79a77f8abe6671a/src/crxviewer.js (line 1687)](https://github.com/Rob--W/crxviewer/blob/96b9e8e08381842c10ba82e5c79a77f8abe6671a/src/crxviewer.js#L1687)

The patterns must be added to cws_patterns.js. Then there are locations where a hardcoded AMO domain is used (e.g. in combination with an add-on ID or slug). That is a bit more difficult, because I want to ensure that the non-dev AMO is used by default, while still supporting alizom. I think that the code should use alizom if alizom is passed in the crx parameter.

Are you interested in a pull request?

**Comment by Rob--W** [comment]
Added support in 1.6.8!
