### ISSUE TITLE
Find more than 25 XPI files of add-ons at AMO

### ISSUE THREAD

**Issue by grahamperrin** [Rob--W/crxviewer#79]
From <https://github.com/Rob--W/crxviewer/issues/39#issuecomment-412137010>

> … only display the 25 most recent versions (and potentially multiple platforms per version). That ought be sufficient, but if not, 

AMO `versions/` pages are limited to twenty-five versions, Mozilla decided to remove and **not** reintroduce the pager.  

> I am willing to add a pager.

Thanks 👍 can you do this? 

Or simply list all versions, when **Search on AMO** is clicked? I imagine that end users of CRX Viewer will be _not_ upset by occasionally long lists.

**Comment by Rob--W** [comment]
Do you have an example of an add-on where over 25 versions are supposedly available but not shown?

The API URL is currently generated at:
https://github.com/Rob--W/crxviewer/blob/0c8a5723863a7e497f6115bf2a59f69c53d49297/src/crxviewer.js#L1688

The default page size is 25, but according to the documentation it can be changed with the `page_size` parameter. There seems also be a `page` parameter, presumably to page through the results. API documentation: https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#versions-list

> Or simply list all versions, when **Search on AMO** is clicked? I imagine that end users of CRX Viewer will be not upset by occasionally long lists.

The API can only return a fixed maximum number of versions. The page limit is because of implementation constraints, not because the fear of long lists.

I would accept pull requests that add a pager to the results (or just a "Show more" button to load more/all pages). The API (see above for link to documentation) also returns `page_count`, `page_size`, `count` and `next`.

**Comment by grahamperrin** [comment]
Thanks. A few examples: 

- https://addons.mozilla.org/addon/enhancer-for-youtube/versions/
- https://addons.mozilla.org/addon/noscript/versions/
- https://addons.mozilla.org/addon/refined-github-/versions/
- https://addons.mozilla.org/addon/ublock-origin/versions/

**Comment by aurora-of-earth** [comment]
@grahamperrin As I see, I can't even view the source code of the historical versions at all.
This issue is pointless.

**Comment by Rob--W** [comment]
Implemented in 1.6.11.

**Comment by grahamperrin** [comment]
Cool! 

Thanks (and sorry that I couldn't do a PR – beyond my skills set). 

![image](https://user-images.githubusercontent.com/192271/62837083-fd0fd180-bc62-11e9-82ce-df18d4bb0f34.png)
