### ISSUE TITLE
Show extension ID of Chrome extension and Firefox add-ons in viewer

### ISSUE THREAD

**Issue by Rob--W** [Rob--W/crxviewer#82]
The extension already has logic to calculate the extension ID for a CRX file (Chrome extension), but it does currently not display it in the interface (except in the console): https://github.com/Rob--W/crxviewer/blob/a18efaae716237781bab7dc562e1b12cb57b6479/src/crxviewer.js#L2068-L2087

There is currently no logic to do the same for a XPI file (Firefox add-on). Signed Firefox add-ons (=all add-ons from AMO) contain the add-on ID in the CN (Common Name) field of the `META-INF/mozilla.rsa` file in the package. Unsigned add-ons *may* have the extension ID in `manifest.json`, either in `applications.gecko.id` or `browser_specific_settings.gecko.id`.
Either value must be a valid add-on ID, i.e. match the [format as specified here](https://searchfox.org/mozilla-central/rev/2738efcf98d746c8810819e7c0634b2c57212a8d/toolkit/components/extensions/schemas/manifest.json#421-431). [Here is the code in Firefox](https://searchfox.org/mozilla-central/rev/2738efcf98d746c8810819e7c0634b2c57212a8d/toolkit/mozapps/extensions/internal/XPIInstall.jsm#565-566) that *uses* the `commonName` field ([here is another one](https://searchfox.org/mozilla-central/rev/2738efcf98d746c8810819e7c0634b2c57212a8d/toolkit/mozapps/extensions/internal/XPIInstall.jsm#640-645,649-671) that uses more fields).

When this is implemented, the information must be displayed in the UI, somewhere.

To do:

- [ ] Implement minimal PKCS#7 parser for the purpose of extracting CN from the certificate. See [RFC 2315](https://tools.ietf.org/html/rfc2315) for the format.
- [ ] Implement function that reads the `META-INF/mozilla.rsa` file and uses the above function to determine the ID. Preferably validate the format of the ID string to avoid showing bogus.
- [ ] Implement logic to extract the ID from `manifest.json` (in case the add-on is unsigned).
- [ ] Implement logic to show the Firefox add-on ID or Chrome extension ID, or none, if applicable.
- [ ] Show the value somewhere in the UI.

**Comment by Lekensteyn** [comment]
The "applications" key is mentioned at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID:
> Note that the ability to develop and debug WebExtensions that don't include an ID is new in Firefox 48. If you need to use an earlier version of Firefox, then you must use the [`applications`][1] key to set an ID explicitly.

but redirects to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings which describes `browser_specific_settings.gecko.id`. It does not document the order where the precedence, but the source code provides more clarity.

If the manifest.json file [exists][2]:
```js
  let bss = (manifest.browser_specific_settings && manifest.browser_specific_settings.gecko)
      || (manifest.applications && manifest.applications.gecko) || {};
  if (manifest.browser_specific_settings && manifest.applications) {
    logger.warn("Ignoring applications property in manifest");
  }
```
If manifest.json does not exist, some name based on `manifestFile` is [looked][3] up, but I could not find other users except for [a test][4].

This appears to be the order of precedence (first existing field will be used):
- if `manifest.browser_specific_settings.gecko` exists in manifest.json, use its `.id` field.
- if `manifest.applications.gecko` exists in manifest.json, use its `.id` field.
- If [neither manifest key exist *or* `id` is undefined][10], basically the name from a certificate (which file, META-INF/mozilla.rsa?) will be used. Details:
  - If the extension is a zip file (as opposed to a directory), and a signature is [required][5] and valid:
    - For the following certificate verification, use the "AddonsPublicRoot". If the Developer Edition is used and the `xpinstall.signatures.dev-root` pref is set, another "AddonsStageRoot" will be used instead (unlikely).
    - Try to [perform certificate validation][7]. Presumably an error is thrown if this fails.
    - If this extension is not signed, try to [find one][8]:
      - If the manifest.json file exists and is successfully parsed as JSON, [extract the ID][9]:
        - Use `applications.gecko.id` as ID (in theory it could be undefined). (Cannot be reached, already handled above.)
        - Else a random UUID is generated and used as ID.
      - If the file name ends on `.xpi`, use the basename (without `.xpi`) as ID. (Irrelevant for crxviewer)
      - (else ID remains undefined).
    - If certificate validation passes, try to use the Subject CommonName (presumably from the first certificate in META-INF/mozilla.rsa) as id.
    - If the discovered CN is not valid (even if it was signed by a trusted CA), an error is thrown.
  - If this is a temporary add-on, then an (effectively) random ID will be generated. (This is not relevant for crxviewer.)
  - (Otherwise the ID remains undefined. I don't think that this can occur for signed add-ons.)

So based on this, it seems that a PKCS \#7 parser would be nice to have as most extensions already have an ID in their manifest.json file right?

 [1]: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/applications
 [2]: https://searchfox.org/mozilla-central/rev/8e0ea968308dd692ba5394b14e584234acf7d4ca/toolkit/mozapps/extensions/internal/XPIInstall.jsm#403-407
 [3]: https://searchfox.org/mozilla-central/rev/2738efcf98d746c8810819e7c0634b2c57212a8d/toolkit/mozapps/extensions/internal/XPIInstall.jsm#540-546
 [4]: https://searchfox.org/mozilla-central/rev/8e0ea968308dd692ba5394b14e584234acf7d4ca/toolkit/mozapps/extensions/test/xpcshell/head_compat.js#14
 [5]: https://searchfox.org/mozilla-central/rev/8e0ea968308dd692ba5394b14e584234acf7d4ca/toolkit/mozapps/extensions/internal/XPIInstall.jsm#692-707
 [6]: https://searchfox.org/mozilla-central/rev/8e0ea968308dd692ba5394b14e584234acf7d4ca/toolkit/mozapps/extensions/internal/XPIInstall.jsm#523-533
 [7]: https://searchfox.org/mozilla-central/rev/8e0ea968308dd692ba5394b14e584234acf7d4ca/toolkit/mozapps/extensions/internal/XPIInstall.jsm#317-335
 [8]: https://searchfox.org/mozilla-central/rev/8e0ea968308dd692ba5394b14e584234acf7d4ca/toolkit/mozapps/extensions/internal/AddonTestUtils.jsm#619-635
 [9]: https://searchfox.org/mozilla-central/rev/8e0ea968308dd692ba5394b14e584234acf7d4ca/toolkit/mozapps/extensions/internal/XPIInstall.jsm#523-533
 [10]: https://searchfox.org/mozilla-central/rev/2738efcf98d746c8810819e7c0634b2c57212a8d/toolkit/mozapps/extensions/internal/XPIInstall.jsm#563-573

**Comment by Rob--W** [comment]
Modify the logic to check the COSE signature before the PKCS#7 signature: https://bugzilla.mozilla.org/show_bug.cgi?id=1471186

The COSE signature is available at `META-INF/cose.sig`. For an example, load [duckduckgo-plus.zip](https://github.com/Rob--W/crxviewer/files/3080600/duckduckgo-plus.zip). (taken from the dev server @ https://addons-dev.allizom.org/en-US/firefox/addon/duckduckgo-plus ).

**Comment by Lekensteyn** [comment]
I just looked at the COSE spec ([RFC 8152](https://tools.ietf.org/html/rfc8152)) in order to build a COSE parser, but it seems that Mozilla has deviated from this (see https://github.com/franziskuskiefer/cose-rust/issues/60).

I have not found a spec from Mozilla, but I suppose I will implement the status quo and read the DER-encoded leaf certificate from `/signatures/protected/kid`, and extract the extension ID from that.

**Comment by Lekensteyn** [comment]
Hi @Rob--W, I have finally pushed the initial working DER and COSE parser. It also includes some testing code, initial testing was done with nodejs, final testing was done with the included HTML file.

Would you like me to submit a (WIP) PR for review or do you want to do it live?
