### ISSUE TITLE
Indent left extension block

### ISSUE THREAD

**Issue by andrecool-68** [Rob--W/crxviewer#89]
The first character of the list on the left merges with the edge of the monitor. 

![000](https://user-images.githubusercontent.com/3471892/79631093-49e76880-815f-11ea-86e9-8a5f8c9f168a.gif)

**Comment by Rob--W** [comment]
This is intentional. The visibility of code is more important than file names, so I have offered a limited amount of space to the file name list. In fact, if the space is too narrow, the left side is cut off. To see the file name with some padding around it, hover over the name so reveal the tooltip.
