### ISSUE TITLE
Stopped working with Brave

### ISSUE THREAD

**Issue by mikhoul** [Rob--W/crxviewer#91]
When I try to look at a source:

![image](https://user-images.githubusercontent.com/5678673/82123238-49de8680-9766-11ea-808d-10388be8cb27.png)

Console: 

![image](https://user-images.githubusercontent.com/5678673/82123273-7d211580-9766-11ea-8250-e069ac67cfaf.png)

Regards :octocat:

**Comment by mikhoul** [comment]
Same thing happen when I try to download a source: 

![image](https://user-images.githubusercontent.com/5678673/82123799-4993ba80-9769-11ea-9b03-97579ffd40a7.png)

**Comment by mikhoul** [comment]
Here the sanitized HAR file: 
[redacted_jifpbeccnghkjeaalbbjmodiffmgedin.zip](https://github.com/Rob--W/crxviewer/files/4638659/redacted_jifpbeccnghkjeaalbbjmodiffmgedin.zip)

**Comment by Rob--W** [comment]
Brave unconditionally intercepts update requests to Google (even if not originating from the browser process...), and replaces it with a request to `go-updater.brave.com`:
https://github.com/brave/brave-core/blob/f453ab2a5e8425afea9bd980fb688d8fec137f53/browser/net/brave_common_static_redirect_network_delegate_helper.cc#L77

Someone reported this issue to me last year, but I unfortunately forgot to follow up to that.

A work-around is to replace "clients2" with "clients3" since they seem to point to the same resources.

Another workaround is to use two slashes in front of the path, since Brave's URL interception logic is based on [a match pattern](https://github.com/brave/brave-core/blob/f453ab2a5e8425afea9bd980fb688d8fec137f53/browser/net/brave_common_static_redirect_network_delegate_helper.cc#L40) that is equivalent to `https://clients2.google.com/service/update2/crx"*` (combined with the [source in Chromium](https://chromium.googlesource.com/chromium/src/+/ef951b429f951b35a02d9bfa36d39e20ef6a0a4a/extensions/common/extension_urls.cc#30)).

I'll look into a way to detect Brave and add a work-around.

**Comment by gslin** [comment]
It seems Brave has changed this code, so `//` not working anymore (tested against `master` branch of crxviewer):

```
bool IsUpdaterURL(const GURL& gurl) {
  static std::vector<URLPattern> updater_patterns(
      {URLPattern(URLPattern::SCHEME_HTTPS,
                  std::string(component_updater::kUpdaterJSONDefaultUrl) + "*"),
       URLPattern(
           URLPattern::SCHEME_HTTP,
           std::string(component_updater::kUpdaterJSONFallbackUrl) + "*"),
#if BUILDFLAG(ENABLE_EXTENSIONS)
       URLPattern(
           URLPattern::SCHEME_HTTPS,
           std::string(extension_urls::kChromeWebstoreUpdateURL) + "*")
#endif
  });
  return std::any_of(
      updater_patterns.begin(), updater_patterns.end(),
      [&gurl](URLPattern pattern) { return pattern.MatchesURL(gurl); });
}
```

**Comment by Rob--W** [comment]
Could you confirm whether version 1.6.12 fixes the issue for you?

**Comment by gslin** [comment]
Cool thanks, I didn't install 1.6.12 but I installed 1.6.11 from Google official webstore and it's working...

Not sure what happened, but anyway it's a good news :-)

**Comment by Rob--W** [comment]
I'll remove the workaround with a future update then, as a cleanup.

On Brave's end this probably started working again due to the changes from https://github.com/brave/brave-core/commit/b3802c6d3b26c0efea4173487a928c1b801d1358
