### ISSUE TITLE
Stop work in Firefox Nightly

### ISSUE THREAD

**Issue by led9** [Rob--W/crxviewer#93]
There is no extension icon in the address bar on extension pages. - the icon is gone.
if you click on the "three dots" icon in the address bar, words "Inspect contents of the current browser extension" not active, gray.
thus there is no error message anywhere.

**Comment by Rob--W** [comment]
Thanks for your report, this is a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1645598

The icon and context menu option are supposedly enabled by default, but due to that bug the default value is lost. To enable the icon in the location bar (and the context menu), visit `about:addons`, click on the "Extension source viewer" entry, click on the "Preferences" tab and check the checkboxes.
